name: sqlbrite
description: RxDart Reactive stream sqflite(sqlite) for Flutter - Sqlbrite for flutter - A lightweight wrapper around sqflite which introduces reactive stream semantics to SQL operations.
version: 2.6.0
homepage: https://github.com/hoc081098/sqlbrite.git
repository: https://github.com/hoc081098/sqlbrite.git
issue_tracker: https://github.com/hoc081098/sqlbrite/issues
funding:
  - https://www.buymeacoffee.com/hoc081098

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart_ext: ^0.2.5
  sqflite: ^2.2.4
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common: ^2.3.0
  sqflite_common_ffi: ^2.1.1+1
  mockito: ^5.3.0
  flutter_lints: ^1.0.4
  build_runner: ^2.2.0
  analyzer: ^5.0.0
  code_builder: ^4.2.0
  path: ^1.8.2
  # flutter packages pub run build_runner build --delete-conflicting-outputs